local RLU = _G["RLU"]

if GetLocale() ~= "deDE" then return end

local L = RLU.L

for key, value in pairs({
    ADDON_NAME = "Reputation Level Up!",
    ABOUT_TAGLINE = "Granulare Reputations-Aufstiegssounds für jede Fraktion in World of Warcraft.",
    WELCOME = "Bereit. Gib |cffffffff/rlu|r ein, um fraktionsspezifische Reputations-Sounds zu konfigurieren.",
    DISABLED = "Addon |cffff0000deaktiviert|r",
    ENABLED = "Addon |cff00ff00aktiviert|r",
    GENERAL = "Allgemein",
    REPUTATIONS = "Reputation",
    ABOUT = "Info",
    OPTIONS_TITLE = "|cff3bbc00R|r|cffffffffeputation |cff3bbc00L|r|cffffffffevel-|cff3bbc00U|r|cffffffffp|cff3bbc00!|r",
    OPTIONS_SUBTITLE = "BLU-artiges v4-Redesign mit nach Erweiterung gruppierten Reputations-Soundzuweisungen",
    PANEL_NAME = "Reputation Level Up!",
    ABOUT_VERSION = "Version: ",
    ABOUT_AUTHOR = "Autor: DonnieDice",
    ABOUT_NOTE = "Dieses v4-Redesign folgt BLUs in sich geschlossener Struktur, der Fokus liegt hier jedoch auf granularem Fraktions-Audio mit Erweiterungs-Gruppierung und einer mitgelieferten Sound-PACK-Bibliothek.",
    DEFAULT_SOUND = "Standard-Reputations-Sound",
    DEFAULT_QUALITY = "Standardqualität",
    GENERAL_INTRO = "ReputationLevelUp v4 nutzt ein BLU-artiges, in sich geschlossenes Setup mit live Fraktions-Gruppierung und granularen Fraktions-Soundzuweisungen.",
    SHOW_LOGIN_MESSAGE = "Anmeldenachricht anzeigen",
    ENABLE_DEBUG_MODE = "Debug-Modus aktivieren",
    TEST_DEFAULT = "Standard testen",
    CURRENT_DEFAULT = "Aktueller Standard: ",
    USE_DEFAULT_ASSIGNMENT = "Standardzuweisung verwenden",
    SOUND_PACKS = "Sound-Packs",
    QUALITY = "Qualität",
    REPUTATIONS_INTRO = "Reputationen sind nach Erweiterung gruppiert. Jede Fraktion kann den Standard-Reputations-Sound mit eigenem Pack und eigener Qualität überschreiben.",
    ASSIGN = "Zuweisen",
    TEST = "Testen",
    BUTTON_FALLBACK = "Schalter",
    CHECKBOX_FALLBACK = "Kontrollkästchen",
    QUALITY_MEDIUM_FALLBACK = "Mittel",
    QUALITY_UNKNOWN = "Unbekannt",
    UNKNOWN_FACTION = "Unbekannte Fraktion",
    SOUND_DEFAULT_REPUTATION = "Standard-Reputation",
    QUALITY_LOW = "Niedrig",
    QUALITY_MED = "Mittel",
    QUALITY_HIGH = "Hoch",
    EXPANSION_CURRENT = "Aktuelle Erweiterung",
    EXPANSION_DRAGONFLIGHT = "Dragonflight",
    EXPANSION_SHADOWLANDS = "Shadowlands",
    EXPANSION_BFA = "Battle for Azeroth",
    EXPANSION_LEGION = "Legion",
    EXPANSION_CLASSIC = "Classic",
    EXPANSION_OTHER = "Andere",
    HELP_COMMANDS = "Befehle: |cffffffff/rlu|r, |cffffffff/rlu help|r, |cffffffff/rlu test|r, |cffffffff/rlu debug|r, |cffffffff/rlu welcome|r, |cffffffff/rlu status|r",
    DEBUG_ENABLED = "Debug-Modus |cff00ff00aktiviert|r.",
    DEBUG_DISABLED = "Debug-Modus |cffff0000deaktiviert|r.",
    LOGIN_ENABLED = "Anmeldenachricht |cff00ff00aktiviert|r.",
    LOGIN_DISABLED = "Anmeldenachricht |cffff0000deaktiviert|r.",
    STATUS_SELECTED_EXPANSION = "Ausgewählte Erweiterung: ",
    STATUS_DEFAULT_SOUND = "Standard-Sound: ",
    VERSION_PREFIX = "Version:",
}) do
    L[key] = value
end
