local RLU = _G["RLU"]

if GetLocale() ~= "esES" then return end

local L = RLU.L

for key, value in pairs({
    ADDON_NAME = "Reputation Level Up!",
    ABOUT_TAGLINE = "Sonidos granulares de subida de reputación para cada facción de World of Warcraft.",
    WELCOME = "Listo. Escribe |cffffffff/rlu|r para configurar sonidos de reputación específicos por facción.",
    DISABLED = "Addon |cffff0000desactivado|r",
    ENABLED = "Addon |cff00ff00activado|r",
    GENERAL = "General",
    REPUTATIONS = "Reputaciones",
    ABOUT = "Acerca de",
    OPTIONS_TITLE = "|cff3bbc00R|r|cffffffffeputation |cff3bbc00L|r|cffffffffevel-|cff3bbc00U|r|cffffffffp|cff3bbc00!|r",
    OPTIONS_SUBTITLE = "Reescritura v4 estilo BLU con asignación de sonidos de reputación agrupada por expansión",
    PANEL_NAME = "Reputation Level Up!",
    ABOUT_VERSION = "Versión: ",
    ABOUT_AUTHOR = "Autor: DonnieDice",
    ABOUT_NOTE = "Esta reescritura v4 refleja la estructura autónoma de BLU, pero aquí el foco es el audio granular por facción con organización por expansión y una biblioteca de paquetes de sonidos integrada.",
    DEFAULT_SOUND = "Sonido de reputación predeterminado",
    DEFAULT_QUALITY = "Calidad predeterminada",
    GENERAL_INTRO = "ReputationLevelUp v4 usa una configuración autónoma estilo BLU con agrupación de facciones en vivo y asignaciones de sonido granulares por facción.",
    SHOW_LOGIN_MESSAGE = "Mostrar mensaje de inicio de sesión",
    ENABLE_DEBUG_MODE = "Activar modo de depuración",
    TEST_DEFAULT = "Probar predeterminado",
    CURRENT_DEFAULT = "Predeterminado actual: ",
    USE_DEFAULT_ASSIGNMENT = "Usar asignación predeterminada",
    SOUND_PACKS = "Paquetes de sonidos",
    QUALITY = "Calidad",
    REPUTATIONS_INTRO = "Las reputaciones se agrupan por expansión. Cada facción puede anular el sonido de reputación predeterminado con su propio paquete y calidad.",
    ASSIGN = "Asignar",
    TEST = "Probar",
    BUTTON_FALLBACK = "Botón",
    CHECKBOX_FALLBACK = "Casilla",
    QUALITY_MEDIUM_FALLBACK = "Media",
    QUALITY_UNKNOWN = "Desconocido",
    UNKNOWN_FACTION = "Facción desconocida",
    SOUND_DEFAULT_REPUTATION = "Reputación predeterminada",
    QUALITY_LOW = "Baja",
    QUALITY_MED = "Media",
    QUALITY_HIGH = "Alta",
    EXPANSION_CURRENT = "Expansión actual",
    EXPANSION_DRAGONFLIGHT = "Dragonflight",
    EXPANSION_SHADOWLANDS = "Shadowlands",
    EXPANSION_BFA = "Battle for Azeroth",
    EXPANSION_LEGION = "Legion",
    EXPANSION_CLASSIC = "Clásico",
    EXPANSION_OTHER = "Otras",
    HELP_COMMANDS = "Comandos: |cffffffff/rlu|r, |cffffffff/rlu help|r, |cffffffff/rlu test|r, |cffffffff/rlu debug|r, |cffffffff/rlu welcome|r, |cffffffff/rlu status|r",
    DEBUG_ENABLED = "Modo de depuración |cff00ff00activado|r.",
    DEBUG_DISABLED = "Modo de depuración |cffff0000desactivado|r.",
    LOGIN_ENABLED = "Mensaje de inicio de sesión |cff00ff00activado|r.",
    LOGIN_DISABLED = "Mensaje de inicio de sesión |cffff0000desactivado|r.",
    STATUS_SELECTED_EXPANSION = "Expansión seleccionada: ",
    STATUS_DEFAULT_SOUND = "Sonido predeterminado: ",
    VERSION_PREFIX = "Versión:",
}) do
    L[key] = value
end
