local RLU = _G["RLU"]

if GetLocale() ~= "frFR" then return end

local L = RLU.L

for key, value in pairs({
    ADDON_NAME = "Reputation Level Up!",
    ABOUT_TAGLINE = "Sons granulaires de passage de réputation pour chaque faction de World of Warcraft.",
    WELCOME = "Prêt. Tapez |cffffffff/rlu|r pour configurer les sons de réputation propres à chaque faction.",
    DISABLED = "Addon |cffff0000désactivé|r",
    ENABLED = "Addon |cff00ff00activé|r",
    GENERAL = "Général",
    REPUTATIONS = "Réputations",
    ABOUT = "À propos",
    OPTIONS_TITLE = "|cff3bbc00R|r|cffffffffeputation |cff3bbc00L|r|cffffffffevel-|cff3bbc00U|r|cffffffffp|cff3bbc00!|r",
    OPTIONS_SUBTITLE = "Réécriture v4 façon BLU avec affectation des sons de réputation groupée par extension",
    PANEL_NAME = "Reputation Level Up!",
    ABOUT_VERSION = "Version : ",
    ABOUT_AUTHOR = "Auteur : DonnieDice",
    ABOUT_NOTE = "Cette réécriture v4 reprend la structure autonome de BLU, mais l'accent est mis ici sur l'audio granulaire par faction avec une organisation par extension et une bibliothèque de packs de sons intégrée.",
    DEFAULT_SOUND = "Son de réputation par défaut",
    DEFAULT_QUALITY = "Qualité par défaut",
    GENERAL_INTRO = "ReputationLevelUp v4 utilise une configuration autonome façon BLU avec regroupement des factions en direct et des affectations de sons granulaires par faction.",
    SHOW_LOGIN_MESSAGE = "Afficher le message de connexion",
    ENABLE_DEBUG_MODE = "Activer le mode débogage",
    TEST_DEFAULT = "Tester le défaut",
    CURRENT_DEFAULT = "Défaut actuel : ",
    USE_DEFAULT_ASSIGNMENT = "Utiliser l'affectation par défaut",
    SOUND_PACKS = "Packs de sons",
    QUALITY = "Qualité",
    REPUTATIONS_INTRO = "Les réputations sont regroupées par extension. Chaque faction peut remplacer le son de réputation par défaut par son propre pack et sa propre qualité.",
    ASSIGN = "Affecter",
    TEST = "Tester",
    BUTTON_FALLBACK = "Bouton",
    CHECKBOX_FALLBACK = "Case à cocher",
    QUALITY_MEDIUM_FALLBACK = "Moyenne",
    QUALITY_UNKNOWN = "Inconnu",
    UNKNOWN_FACTION = "Faction inconnue",
    SOUND_DEFAULT_REPUTATION = "Réputation par défaut",
    QUALITY_LOW = "Basse",
    QUALITY_MED = "Moyenne",
    QUALITY_HIGH = "Haute",
    EXPANSION_CURRENT = "Extension actuelle",
    EXPANSION_DRAGONFLIGHT = "Dragonflight",
    EXPANSION_SHADOWLANDS = "Shadowlands",
    EXPANSION_BFA = "Battle for Azeroth",
    EXPANSION_LEGION = "Legion",
    EXPANSION_CLASSIC = "Classic",
    EXPANSION_OTHER = "Autres",
    HELP_COMMANDS = "Commandes : |cffffffff/rlu|r, |cffffffff/rlu help|r, |cffffffff/rlu test|r, |cffffffff/rlu debug|r, |cffffffff/rlu welcome|r, |cffffffff/rlu status|r",
    DEBUG_ENABLED = "Mode débogage |cff00ff00activé|r.",
    DEBUG_DISABLED = "Mode débogage |cffff0000désactivé|r.",
    LOGIN_ENABLED = "Message de connexion |cff00ff00activé|r.",
    LOGIN_DISABLED = "Message de connexion |cffff0000désactivé|r.",
    STATUS_SELECTED_EXPANSION = "Extension sélectionnée : ",
    STATUS_DEFAULT_SOUND = "Son par défaut : ",
    VERSION_PREFIX = "Version :",
}) do
    L[key] = value
end
