local RLU = _G["RLU"]

if GetLocale() ~= "itIT" then return end

local L = RLU.L

for key, value in pairs({
    ADDON_NAME = "Reputation Level Up!",
    ABOUT_TAGLINE = "Suoni granulari di aumento reputazione per ogni fazione di World of Warcraft.",
    WELCOME = "Pronto. Digita |cffffffff/rlu|r per configurare suoni di reputazione specifici per fazione.",
    DISABLED = "Addon |cffff0000disattivato|r",
    ENABLED = "Addon |cff00ff00attivato|r",
    GENERAL = "Generale",
    REPUTATIONS = "Reputazioni",
    ABOUT = "Informazioni",
    OPTIONS_TITLE = "|cff3bbc00R|r|cffffffffeputation |cff3bbc00L|r|cffffffffevel-|cff3bbc00U|r|cffffffffp|cff3bbc00!|r",
    OPTIONS_SUBTITLE = "Riscrittura v4 in stile BLU con assegnazione dei suoni di reputazione raggruppata per espansione",
    PANEL_NAME = "Reputation Level Up!",
    ABOUT_VERSION = "Versione: ",
    ABOUT_AUTHOR = "Autore: DonnieDice",
    ABOUT_NOTE = "Questa riscrittura v4 riprende la struttura autonoma di BLU, ma qui il fulcro è l'audio granulare per fazione con organizzazione per espansione e una libreria di pacchetti sonori integrata.",
    DEFAULT_SOUND = "Suono reputazione predefinito",
    DEFAULT_QUALITY = "Qualità predefinita",
    GENERAL_INTRO = "ReputationLevelUp v4 usa una configurazione autonoma in stile BLU con raggruppamento delle fazioni in tempo reale e assegnazioni sonore granulari per fazione.",
    SHOW_LOGIN_MESSAGE = "Mostra messaggio di accesso",
    ENABLE_DEBUG_MODE = "Attiva modalità debug",
    TEST_DEFAULT = "Prova predefinito",
    CURRENT_DEFAULT = "Predefinito attuale: ",
    USE_DEFAULT_ASSIGNMENT = "Usa assegnazione predefinita",
    SOUND_PACKS = "Pacchetti sonori",
    QUALITY = "Qualità",
    REPUTATIONS_INTRO = "Le reputazioni sono raggruppate per espansione. Ogni fazione può sovrascrivere il suono di reputazione predefinito con il proprio pacchetto e la propria qualità.",
    ASSIGN = "Assegna",
    TEST = "Prova",
    BUTTON_FALLBACK = "Pulsante",
    CHECKBOX_FALLBACK = "Casella di spunta",
    QUALITY_MEDIUM_FALLBACK = "Media",
    QUALITY_UNKNOWN = "Sconosciuto",
    UNKNOWN_FACTION = "Fazione sconosciuta",
    SOUND_DEFAULT_REPUTATION = "Reputazione predefinita",
    QUALITY_LOW = "Bassa",
    QUALITY_MED = "Media",
    QUALITY_HIGH = "Alta",
    EXPANSION_CURRENT = "Espansione attuale",
    EXPANSION_DRAGONFLIGHT = "Dragonflight",
    EXPANSION_SHADOWLANDS = "Shadowlands",
    EXPANSION_BFA = "Battle for Azeroth",
    EXPANSION_LEGION = "Legion",
    EXPANSION_CLASSIC = "Classico",
    EXPANSION_OTHER = "Altro",
    HELP_COMMANDS = "Comandi: |cffffffff/rlu|r, |cffffffff/rlu help|r, |cffffffff/rlu test|r, |cffffffff/rlu debug|r, |cffffffff/rlu welcome|r, |cffffffff/rlu status|r",
    DEBUG_ENABLED = "Modalità debug |cff00ff00attivata|r.",
    DEBUG_DISABLED = "Modalità debug |cffff0000disattivata|r.",
    LOGIN_ENABLED = "Messaggio di accesso |cff00ff00attivato|r.",
    LOGIN_DISABLED = "Messaggio di accesso |cffff0000disattivato|r.",
    STATUS_SELECTED_EXPANSION = "Espansione selezionata: ",
    STATUS_DEFAULT_SOUND = "Suono predefinito: ",
    VERSION_PREFIX = "Versione:",
}) do
    L[key] = value
end
