local RLU = _G["RLU"]

if GetLocale() ~= "koKR" then return end

local L = RLU.L

for key, value in pairs({
    ADDON_NAME = "레벨 업 평판!",
    ABOUT_TAGLINE = "월드 오브 워크래프트의 모든 진영을 위한 세분화된 평판 상승 사운드.",
    WELCOME = "준비 완료. |cffffffff/rlu|r을(를) 입력하여 진영별 평판 사운드를 설정하세요.",
    DISABLED = "애드온 |cffff0000비활성화됨|r",
    ENABLED = "애드온 |cff00ff00활성화됨|r",
    GENERAL = "일반",
    REPUTATIONS = "평판",
    ABOUT = "정보",
    OPTIONS_TITLE = "|cff3bbc00레|r|cffffffff벨 업 평판|cff3bbc00!|r",
    OPTIONS_SUBTITLE = "확장팩별로 묶인 평판 사운드 할당 기능을 갖춘 BLU 방식 v4 리라이트",
    PANEL_NAME = "레벨 업 평판!",
    ABOUT_VERSION = "버전: ",
    ABOUT_AUTHOR = "제작자: DonnieDice",
    ABOUT_NOTE = "이 v4 리라이트는 BLU의 독립적인 구조를 따르지만, 여기서는 확장팩별 구성과 함께 제공되는 사운드 팩 라이브러리를 활용한 세분화된 진영별 오디오에 중점을 둡니다.",
    DEFAULT_SOUND = "기본 평판 사운드",
    DEFAULT_QUALITY = "기본 품질",
    GENERAL_INTRO = "ReputationLevelUp v4는 실시간 진영 묶음과 세분화된 진영별 사운드 할당 기능을 갖춘 BLU 방식의 독립적인 구성을 사용합니다.",
    SHOW_LOGIN_MESSAGE = "로그인 메시지 표시",
    ENABLE_DEBUG_MODE = "디버그 모드 활성화",
    TEST_DEFAULT = "기본값 테스트",
    CURRENT_DEFAULT = "현재 기본값: ",
    USE_DEFAULT_ASSIGNMENT = "기본 할당 사용",
    SOUND_PACKS = "사운드 팩",
    QUALITY = "품질",
    REPUTATIONS_INTRO = "평판은 확장팩별로 묶입니다. 각 진영은 자체 사운드 팩과 품질로 기본 평판 사운드를 재정의할 수 있습니다.",
    ASSIGN = "할당",
    TEST = "테스트",
    BUTTON_FALLBACK = "버튼",
    CHECKBOX_FALLBACK = "확인란",
    QUALITY_MEDIUM_FALLBACK = "중간",
    QUALITY_UNKNOWN = "알 수 없음",
    UNKNOWN_FACTION = "알 수 없는 진영",
    SOUND_DEFAULT_REPUTATION = "기본 평판",
    QUALITY_LOW = "낮음",
    QUALITY_MED = "중간",
    QUALITY_HIGH = "높음",
    EXPANSION_CURRENT = "최신 확장팩",
    EXPANSION_DRAGONFLIGHT = "드래곤플라이트",
    EXPANSION_SHADOWLANDS = "섀도우랜드",
    EXPANSION_BFA = "격전의 아제로스",
    EXPANSION_LEGION = "군단",
    EXPANSION_CLASSIC = "클래식",
    EXPANSION_OTHER = "기타",
    HELP_COMMANDS = "명령어: |cffffffff/rlu|r, |cffffffff/rlu help|r, |cffffffff/rlu test|r, |cffffffff/rlu debug|r, |cffffffff/rlu welcome|r, |cffffffff/rlu status|r",
    DEBUG_ENABLED = "디버그 모드 |cff00ff00활성화됨|r.",
    DEBUG_DISABLED = "디버그 모드 |cffff0000비활성화됨|r.",
    LOGIN_ENABLED = "로그인 메시지 |cff00ff00활성화됨|r.",
    LOGIN_DISABLED = "로그인 메시지 |cffff0000비활성화됨|r.",
    STATUS_SELECTED_EXPANSION = "선택된 확장팩: ",
    STATUS_DEFAULT_SOUND = "기본 사운드: ",
    VERSION_PREFIX = "버전: ",
}) do
    L[key] = value
end
