local RLU = _G["RLU"]

if GetLocale() ~= "ptPT" then return end

local L = RLU.L

for key, value in pairs({
    ADDON_NAME = "Reputation Level Up!",
    ABOUT_TAGLINE = "Sons granulares de subida de reputação para cada facção de World of Warcraft.",
    WELCOME = "Pronto. Escreve |cffffffff/rlu|r para configurar sons de reputação específicos por facção.",
    DISABLED = "Addon |cffff0000desativado|r",
    ENABLED = "Addon |cff00ff00ativado|r",
    GENERAL = "Geral",
    REPUTATIONS = "Reputações",
    ABOUT = "Sobre",
    OPTIONS_TITLE = "|cff3bbc00R|r|cffffffffeputation |cff3bbc00L|r|cffffffffevel-|cff3bbc00U|r|cffffffffp|cff3bbc00!|r",
    OPTIONS_SUBTITLE = "Reescrita v4 ao estilo BLU com atribuição de sons de reputação agrupada por expansão",
    PANEL_NAME = "Reputation Level Up!",
    ABOUT_VERSION = "Versão: ",
    ABOUT_AUTHOR = "Autor: DonnieDice",
    ABOUT_NOTE = "Esta reescrita v4 espelha a estrutura autónoma do BLU, mas o foco aqui é o áudio granular por facção com organização por expansão e uma biblioteca de pacotes de sons integrada.",
    DEFAULT_SOUND = "Som de reputação predefinido",
    DEFAULT_QUALITY = "Qualidade predefinida",
    GENERAL_INTRO = "O ReputationLevelUp v4 usa uma configuração autónoma ao estilo BLU com agrupamento de facções em direto e atribuições de sons granulares por facção.",
    SHOW_LOGIN_MESSAGE = "Mostrar mensagem de início de sessão",
    ENABLE_DEBUG_MODE = "Ativar modo de depuração",
    TEST_DEFAULT = "Testar predefinição",
    CURRENT_DEFAULT = "Predefinição atual: ",
    USE_DEFAULT_ASSIGNMENT = "Usar atribuição predefinida",
    SOUND_PACKS = "Pacotes de sons",
    QUALITY = "Qualidade",
    REPUTATIONS_INTRO = "As reputações são agrupadas por expansão. Cada facção pode substituir o som de reputação predefinido pelo seu próprio pacote e qualidade.",
    ASSIGN = "Atribuir",
    TEST = "Testar",
    BUTTON_FALLBACK = "Botão",
    CHECKBOX_FALLBACK = "Caixa de verificação",
    QUALITY_MEDIUM_FALLBACK = "Média",
    QUALITY_UNKNOWN = "Desconhecido",
    UNKNOWN_FACTION = "Facção desconhecida",
    SOUND_DEFAULT_REPUTATION = "Reputação predefinida",
    QUALITY_LOW = "Baixa",
    QUALITY_MED = "Média",
    QUALITY_HIGH = "Alta",
    EXPANSION_CURRENT = "Expansão atual",
    EXPANSION_DRAGONFLIGHT = "Dragonflight",
    EXPANSION_SHADOWLANDS = "Shadowlands",
    EXPANSION_BFA = "Battle for Azeroth",
    EXPANSION_LEGION = "Legion",
    EXPANSION_CLASSIC = "Clássico",
    EXPANSION_OTHER = "Outras",
    HELP_COMMANDS = "Comandos: |cffffffff/rlu|r, |cffffffff/rlu help|r, |cffffffff/rlu test|r, |cffffffff/rlu debug|r, |cffffffff/rlu welcome|r, |cffffffff/rlu status|r",
    DEBUG_ENABLED = "Modo de depuração |cff00ff00ativado|r.",
    DEBUG_DISABLED = "Modo de depuração |cffff0000desativado|r.",
    LOGIN_ENABLED = "Mensagem de início de sessão |cff00ff00ativada|r.",
    LOGIN_DISABLED = "Mensagem de início de sessão |cffff0000desativada|r.",
    STATUS_SELECTED_EXPANSION = "Expansão selecionada: ",
    STATUS_DEFAULT_SOUND = "Som predefinido: ",
    VERSION_PREFIX = "Versão: ",
}) do
    L[key] = value
end
