local RLU = _G["RLU"]

if GetLocale() ~= "ruRU" then return end

local L = RLU.L

for key, value in pairs({
    ADDON_NAME = "Reputation Level Up!",
    ABOUT_TAGLINE = "Детализированные звуки повышения репутации для каждой фракции World of Warcraft.",
    WELCOME = "Готово. Введите |cffffffff/rlu|r, чтобы настроить звуки репутации для отдельных фракций.",
    DISABLED = "Аддон |cffff0000отключён|r",
    ENABLED = "Аддон |cff00ff00включён|r",
    GENERAL = "Основные",
    REPUTATIONS = "Репутация",
    ABOUT = "Об аддоне",
    OPTIONS_TITLE = "|cff3bbc00Р|r|cffffffffепутация — |cff3bbc00П|r|cffffffffодъём!|r",
    OPTIONS_SUBTITLE = "Переработка v4 в стиле BLU с распределением звуков репутации по дополнениям",
    PANEL_NAME = "Reputation Level Up!",
    ABOUT_VERSION = "Версия: ",
    ABOUT_AUTHOR = "Автор: DonnieDice",
    ABOUT_NOTE = "Эта переработка v4 повторяет автономную структуру BLU, но здесь основной упор сделан на детализированное аудио для каждой фракции с группировкой по дополнениям и встроенной библиотекой наборов звуков.",
    DEFAULT_SOUND = "Звук репутации по умолчанию",
    DEFAULT_QUALITY = "Качество по умолчанию",
    GENERAL_INTRO = "ReputationLevelUp v4 использует автономную структуру в стиле BLU с динамической группировкой фракций и детализированным назначением звуков для каждой фракции.",
    SHOW_LOGIN_MESSAGE = "Показывать сообщение при входе",
    ENABLE_DEBUG_MODE = "Включить режим отладки",
    TEST_DEFAULT = "Проверить стандартный",
    CURRENT_DEFAULT = "Текущий стандарт: ",
    USE_DEFAULT_ASSIGNMENT = "Использовать стандартное назначение",
    SOUND_PACKS = "Наборы звуков",
    QUALITY = "Качество",
    REPUTATIONS_INTRO = "Репутации сгруппированы по дополнениям. Каждая фракция может заменить стандартный звук репутации собственным набором и качеством.",
    ASSIGN = "Назначить",
    TEST = "Проверить",
    BUTTON_FALLBACK = "Кнопка",
    CHECKBOX_FALLBACK = "Галочка",
    QUALITY_MEDIUM_FALLBACK = "Среднее",
    QUALITY_UNKNOWN = "Неизвестно",
    UNKNOWN_FACTION = "Неизвестная фракция",
    SOUND_DEFAULT_REPUTATION = "Репутация по умолчанию",
    QUALITY_LOW = "Низкое",
    QUALITY_MED = "Среднее",
    QUALITY_HIGH = "Высокое",
    EXPANSION_CURRENT = "Текущее дополнение",
    EXPANSION_DRAGONFLIGHT = "Dragonflight",
    EXPANSION_SHADOWLANDS = "Shadowlands",
    EXPANSION_BFA = "Battle for Azeroth",
    EXPANSION_LEGION = "Legion",
    EXPANSION_CLASSIC = "Классик",
    EXPANSION_OTHER = "Прочее",
    HELP_COMMANDS = "Команды: |cffffffff/rlu|r, |cffffffff/rlu help|r, |cffffffff/rlu test|r, |cffffffff/rlu debug|r, |cffffffff/rlu welcome|r, |cffffffff/rlu status|r",
    DEBUG_ENABLED = "Режим отладки |cff00ff00включён|r.",
    DEBUG_DISABLED = "Режим отладки |cffff0000отключён|r.",
    LOGIN_ENABLED = "Сообщение при входе |cff00ff00включено|r.",
    LOGIN_DISABLED = "Сообщение при входе |cffff0000отключено|r.",
    STATUS_SELECTED_EXPANSION = "Выбранное дополнение: ",
    STATUS_DEFAULT_SOUND = "Стандартный звук: ",
    VERSION_PREFIX = "Версия:",
}) do
    L[key] = value
end
