local RLU = _G["RLU"]

if GetLocale() ~= "zhCN" then return end

local L = RLU.L

for key, value in pairs({
    ADDON_NAME = "声望升级！",
    ABOUT_TAGLINE = "为《魔兽世界》每个阵营提供精细的声望提升音效。",
    WELCOME = "已就绪。输入 |cffffffff/rlu|r 配置各阵营专属声望音效。",
    DISABLED = "插件已|cffff0000禁用|r",
    ENABLED = "插件已|cff00ff00启用|r",
    GENERAL = "常规",
    REPUTATIONS = "声望",
    ABOUT = "关于",
    OPTIONS_TITLE = "|cff3bbc00声|r|cffffffff望升级|cff3bbc00！|r",
    OPTIONS_SUBTITLE = "BLU 风格的 v4 重写版，按资料片分组分配声望音效",
    PANEL_NAME = "声望升级！",
    ABOUT_VERSION = "版本：",
    ABOUT_AUTHOR = "作者：DonnieDice",
    ABOUT_NOTE = "本次 v4 重写沿用了 BLU 的自包含结构，但重点在于按资料片组织的精细化阵营音效，并附带音效包库。",
    DEFAULT_SOUND = "默认声望音效",
    DEFAULT_QUALITY = "默认音质",
    GENERAL_INTRO = "ReputationLevelUp v4 采用 BLU 风格的自包含结构，支持实时阵营分组和精细的各阵营音效分配。",
    SHOW_LOGIN_MESSAGE = "显示登录消息",
    ENABLE_DEBUG_MODE = "启用调试模式",
    TEST_DEFAULT = "测试默认音效",
    CURRENT_DEFAULT = "当前默认：",
    USE_DEFAULT_ASSIGNMENT = "使用默认分配",
    SOUND_PACKS = "音效包",
    QUALITY = "音质",
    REPUTATIONS_INTRO = "声望按资料片分组。每个阵营都可以用自己的音效包和音质覆盖默认声望音效。",
    ASSIGN = "分配",
    TEST = "测试",
    BUTTON_FALLBACK = "按钮",
    CHECKBOX_FALLBACK = "复选框",
    QUALITY_MEDIUM_FALLBACK = "中",
    QUALITY_UNKNOWN = "未知",
    UNKNOWN_FACTION = "未知阵营",
    SOUND_DEFAULT_REPUTATION = "默认声望",
    QUALITY_LOW = "低",
    QUALITY_MED = "中",
    QUALITY_HIGH = "高",
    EXPANSION_CURRENT = "当前资料片",
    EXPANSION_DRAGONFLIGHT = "巨龙时代",
    EXPANSION_SHADOWLANDS = "暗影国度",
    EXPANSION_BFA = "争霸艾泽拉斯",
    EXPANSION_LEGION = "军团再临",
    EXPANSION_CLASSIC = "经典旧世",
    EXPANSION_OTHER = "其他",
    HELP_COMMANDS = "命令：|cffffffff/rlu|r、|cffffffff/rlu help|r、|cffffffff/rlu test|r、|cffffffff/rlu debug|r、|cffffffff/rlu welcome|r、|cffffffff/rlu status|r",
    DEBUG_ENABLED = "调试模式已|cff00ff00启用|r。",
    DEBUG_DISABLED = "调试模式已|cffff0000禁用|r。",
    LOGIN_ENABLED = "登录消息已|cff00ff00启用|r。",
    LOGIN_DISABLED = "登录消息已|cffff0000禁用|r。",
    STATUS_SELECTED_EXPANSION = "已选资料片：",
    STATUS_DEFAULT_SOUND = "默认音效：",
    VERSION_PREFIX = "版本：",
}) do
    L[key] = value
end
