local RLU = _G["RLU"]

if GetLocale() ~= "zhTW" then return end

local L = RLU.L

for key, value in pairs({
    ADDON_NAME = "聲望升級！",
    ABOUT_TAGLINE = "為《魔獸世界》每個陣營提供精細的聲望提升音效。",
    WELCOME = "已就緒。輸入 |cffffffff/rlu|r 設定各陣營專屬聲望音效。",
    DISABLED = "插件已|cffff0000停用|r",
    ENABLED = "插件已|cff00ff00啟用|r",
    GENERAL = "一般",
    REPUTATIONS = "聲望",
    ABOUT = "關於",
    OPTIONS_TITLE = "|cff3bbc00聲|r|cffffffff望升級|cff3bbc00！|r",
    OPTIONS_SUBTITLE = "BLU 風格的 v4 重寫版，按資料片分組分配聲望音效",
    PANEL_NAME = "聲望升級！",
    ABOUT_VERSION = "版本：",
    ABOUT_AUTHOR = "作者：DonnieDice",
    ABOUT_NOTE = "本次 v4 重寫沿用 BLU 的自包含架構，但重點在於按資料片組織的精細陣營音效，並內建音效包庫。",
    DEFAULT_SOUND = "預設聲望音效",
    DEFAULT_QUALITY = "預設音質",
    GENERAL_INTRO = "ReputationLevelUp v4 採用 BLU 風格的自包含架構，支援即時陣營分組與精細的各陣營音效分配。",
    SHOW_LOGIN_MESSAGE = "顯示登入訊息",
    ENABLE_DEBUG_MODE = "啟用除錯模式",
    TEST_DEFAULT = "測試預設",
    CURRENT_DEFAULT = "目前預設：",
    USE_DEFAULT_ASSIGNMENT = "使用預設分配",
    SOUND_PACKS = "音效包",
    QUALITY = "音質",
    REPUTATIONS_INTRO = "聲望按資料片分組。每個陣營都可以用自己的音效包和音質覆寫預設聲望音效。",
    ASSIGN = "分配",
    TEST = "測試",
    BUTTON_FALLBACK = "按鈕",
    CHECKBOX_FALLBACK = "核取方塊",
    QUALITY_MEDIUM_FALLBACK = "中",
    QUALITY_UNKNOWN = "未知",
    UNKNOWN_FACTION = "未知陣營",
    SOUND_DEFAULT_REPUTATION = "預設聲望",
    QUALITY_LOW = "低",
    QUALITY_MED = "中",
    QUALITY_HIGH = "高",
    EXPANSION_CURRENT = "目前資料片",
    EXPANSION_DRAGONFLIGHT = "巨龍崛起",
    EXPANSION_SHADOWLANDS = "暗影之境",
    EXPANSION_BFA = "決戰艾澤拉斯",
    EXPANSION_LEGION = "軍臨天下",
    EXPANSION_CLASSIC = "經典版",
    EXPANSION_OTHER = "其他",
    HELP_COMMANDS = "命令：|cffffffff/rlu|r、|cffffffff/rlu help|r、|cffffffff/rlu test|r、|cffffffff/rlu debug|r、|cffffffff/rlu welcome|r、|cffffffff/rlu status|r",
    DEBUG_ENABLED = "除錯模式已|cff00ff00啟用|r。",
    DEBUG_DISABLED = "除錯模式已|cffff0000停用|r。",
    LOGIN_ENABLED = "登入訊息已|cff00ff00啟用|r。",
    LOGIN_DISABLED = "登入訊息已|cffff0000停用|r。",
    STATUS_SELECTED_EXPANSION = "已選資料片：",
    STATUS_DEFAULT_SOUND = "預設音效：",
    VERSION_PREFIX = "版本：",
}) do
    L[key] = value
end
